### PR TITLE
Use optional-lite for optional

### PR DESCRIPTION
**Pull request by charliewolf**
The `optional` module you're using doesn't use the STL `optional` when it's available (theoretically any compliant C++17 compiler). This means, especially on Macs where optional is under std::experimental, it'll clobber the real `optional` provided by the STL. `optional-lite` will respect an existing system `optional` library.

**Important:** I didn't regenerate the single_header file because you don't seem to have instructions on how to do that. That should be done before this is merged.

### CODE REVIEW

**Comment by SaadAttieh** [comment]
Hey, Thanks for this.  I remember this being at the back of my mind when I first tested out the library.  I want to merge this in but I wanted to check first:  Is there a reason you switched from external project add to adding sub directories?  My CMAKE knowledge is not the best, but as far as I know from reading around, the more modern method of managing dependancies is via external project add.  It prevents issues such as those caused by multiple libs including the same project as a sub directory.  

I'll also push my script for building a single header today.

**Comment by charliewolf** [comment]
@SaadAttieh Well, of course it's a matter of preference, but I prefer the git submodule approach because it is more idempotent--you know you're building the revision you added as a submodule. Right now, if the `optional` API changed in master, your code would break. Also, using an ExternalProject that pulls from github means the process that builds the software needs internet access. With a submodule, only the process that clones needs the internet (in a lot of CI environments, the actual builder might not have a network connection for security reasons.)

If you're concerned about multiple libs including it you could guard it with `if(NOT TARGET optional-lite)`

**Comment by charliewolf** [comment]
@SaadAttieh I rebased this, generated the single header, and put the `optional-lite` CMake subdirectory command under an `if NOT TARGET` guard.

**Comment by SaadAttieh** [comment]
Awesome, you beat me to it, great thanks. I'LL merge it in tomorrow. I'm not sure I'm convinced by having dependencies as sub directories instead of external projects. Nevertheless, it has been the way to do it for a while so it's prob not a big deal to switch over. Appreciate the help, I would be interested in your feedback on the lib in general. I am planning on adding some features such as a forEach Parallel and  a generator composer which will allow generators to emulate the behaviour of nested for loops.

**Pull request merged**
